dataset:
  processed_path: "./data/processed/maestro_spectrograms_test/"
  target_time_frames: 256

vqvae:
  # Update to your latest trained Jukebox VQ-VAE runs per level.
  top_model_dir: "./models/jukebox_vq_vae/jukebox_vqvae_maestro2011_top/2026-03-22_09-41-44"
  middle_model_dir: "./models/jukebox_vq_vae/jukebox_vqvae_maestro2011_middle/2026-03-22_06-54-25"
  bottom_model_dir: "./models/jukebox_vq_vae/jukebox_vqvae_maestro2011_bottom/2026-03-22_03-23-39"
  weights_file: "best_model.pth"

model:
  name: "jukebox_maestro2011"

# Configurations related to the upsampler are calculated in the script, example:
# the python training script will read the VQ-VAE configs to determine the number of tokens at each level,
# and then set the upsample_stride for each prior accordingly
# (e.g., Middle upsample_stride = 256/64 = 4, Bottom upsample_stride = 1024/256 = 4).
# This way, your priors will be perfectly aligned with your VQ-VAE's latent space structure without
# needing to hardcode those details here.
priors:
  top_prior:
    model_dim: 512
    num_heads: 8
    num_layers: 12
    dim_feedforward: 2048
    dropout: 0.1
    block_len: 8  # Because Top grid is 8x8
  middle_prior:
    model_dim: 512
    num_heads: 8
    num_layers: 12
    dim_feedforward: 2048
    dropout: 0.1
    block_len: 16  # Because Middle grid is 16x16
  bottom_prior:
    model_dim: 512
    num_heads: 8
    num_layers: 12
    dim_feedforward: 2048
    dropout: 0.1
    block_len: 32  # Because Bottom grid is 32x32
    # condiditioner parameters
    conditioner_residual_block_width: 1024
    conditioner_residual_blocks: 16
    conditioner_kernel_size: 3
    conditioner_conv_channels: 1024
    conditioner_dilation_growth_rate: 3
    conditioner_dilation_cycle: 8
    conditioner_upsample_stride: 4 # Because Bottom grid is 32x32 and Middle grid is 16x16, we need to upsample by a factor of 2 in

training:
  batch_size: 16
  quantization_batch_size: 32
  learning_rate: 0.0003  # Warmup to lr then cosine decay
  weight_decay: 0.01
  epochs: 150
  validation_split: 0.2
  early_stopping_patience: 7
  save_dir: "./models/transformer_prior/"
