dataset:
  processed_path: ./data/processed/maestro_spectrograms_test/
  target_time_frames: 256
model:
  inferred_grids:
    bottom:
    - 32
    - 32
    middle:
    - 16
    - 16
    top:
    - 8
    - 8
  inferred_seq_lens:
    bottom: 1024
    middle: 256
    top: 64
  inferred_upsample_stride: 4
  name: jukebox_maestro2011
  selected_level: bottom
priors:
  bottom_prior:
    block_len: 16
    dim_feedforward: 2048
    dropout: 0.1
    model_dim: 512
    num_heads: 8
    num_layers: 12
  middle_prior:
    block_len: 16
    dim_feedforward: 2048
    dropout: 0.1
    model_dim: 512
    num_heads: 8
    num_layers: 12
  top_prior:
    block_len: 16
    dim_feedforward: 2048
    dropout: 0.1
    model_dim: 512
    num_heads: 8
    num_layers: 12
training:
  batch_size: 16
  early_stopping_patience: 10
  epochs: 150
  learning_rate: 0.0003
  quantization_batch_size: 32
  save_dir: ./models/transformer_prior/
  validation_split: 0.2
  weight_decay: 0.01
vqvae:
  bottom_model_dir: ./models/jukebox_vq_vae/jukebox_vqvae_maestro2011_bottom/2026-03-09_01-09-07
  middle_model_dir: ./models/jukebox_vq_vae/jukebox_vqvae_maestro2011_middle/2026-03-09_04-38-06
  top_model_dir: ./models/jukebox_vq_vae/jukebox_vqvae_maestro2011_top/2026-03-09_08-30-58
  weights_file: best_model.pth
